/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/U3Og5iKKE7x
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export default function feedback() {
  return (
    <div className="mx-auto max-w-md md:max-w-[60%] space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Give us your feedback</h1>
        <p className="text-gray-500 dark:text-gray-400">Help us improve our product by sharing your thoughts.</p>
      </div>
      <form className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="name">Name</Label>
          <Input id="name" placeholder="Enter your name" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" type="email" placeholder="Enter your email" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="feedback">Feedback</Label>
          <Textarea id="feedback" placeholder="Share your feedback" required />
        </div>
        <Button type="submit" className="w-full">
          Submit Feedback
        </Button>
      </form>
    </div>
  )
}
